### ISSUE TITLE
Duplicate too zoomed in sources

### ISSUE THREAD

**Issue by jcroston** [mhardcastle/lgz#12]
Beatriz has spotted that there are some duplicate source names in the current main table. These all have ID_flag==312, i.e. too zoomed in sources from LGZv1. In some cases the duplicate entries have different coordinates and fluxes, etc. There is a table of these entries on lofar.herts here: /data/lofar/bmingo/morph/hetdex/Multi_rows.fits .

**Comment by bmingo** [comment]
Some have ID_flag==322 as well (still too zoomed in, from LGZv2)

**Comment by wndywllms** [comment]
@mhardcastle looks like these are coming from lgz_components.txt 

Seems like the New_Source_Name is not updated when the next source from the too-zoomed-in route doesn't get a new name...
ILTJ105520.42+535327.4 ILTJ105520.65+535327.8 2
ILTJ105520.87+535328.2 ILTJ105520.65+535327.8 2
ILTJ131113.89+532359.1 ILTJ105520.65+535327.8 2
ILTJ143422.67+484531.9 ILTJ105520.65+535327.8 2

**Comment by mhardcastle** [comment]
Yep, giant bug in my code; a whole bunch of sources will have the same source name as the first source in the list.

Just testing a fix now. Tim is going to provide a new pybdsf catalogue that'll fix #8 and #10 as well, so once we have that we can do a new release.

**Comment by mhardcastle** [comment]
Fixed in commit ccf8aac3b313d6e32d98e711a6787a0baeb2804e.

**Comment by mhardcastle** [comment]
Please check the new catalogues uploaded just now on the release site and close this if the problem's resolved. (I have to go and watch a nativity play...)

**Comment by bmingo** [comment]
Commenting here, as I suspect it is related. 

On the new version of the components table, the New_Source_Name seems to be associated to components with very different RA/DEC, e.g.:
Source ILTJ124152.30+492456.1, RA: 190.4678993205904, DEC: 49.415595368552474
Associated components:
ILTJ141727.63+561903.6, RA: 214.36511078446716, DEC: 56.317666900775215
ILTJ141731.31+551721.8, RA: 214.38045787418406, DEC: 55.28939075359578

Source ILTJ110724.95+480111.6, RA: 166.85395131344876, DEC: 48.019888921612996
Components:
ILTJ140359.98+541150.7, RA: 210.99993191797194, DEC: 54.19743273956141
ILTJ140401.56+483134.5, RA: 211.00648927518776, DEC: 48.52626391684067

This seems to be the case for all sources with multiple components, looking at the Source_Name vs New_Source_Name discrepancy on the table.

Probably unrelated, but still important (let me know if you want me to put this on a separate thread):
-There is a duplicate entry in the main table (ID=ILTJ132633.10+484745.7, ID_flag=1)

Maybe unrelated, less important, but will need looking into at some point (let me know if you want me to put this on a separate thread):
-There are 162 sources (160 from LGZ, **EDIT** with ID_Flag mostly 311, some 312, a few 322, plus the two from the duplicated entry above) for which the number of components listed on the main table and the number of associated entries in the components catalogue are different (in some cases, the number of entries in the components table is larger, in some cases smaller).

**Comment by mhardcastle** [comment]
This sounds like the original problem hasn't been solved at all. Which is strange, because these files are right in `lgz_components.txt`:

```
[mjh@lofar-server lofar]$ cd /data/lofar/mjh/hetdex_v4/lgz_v1
[mjh@lofar-server lgz_v1]$ grep ILTJ141727.63+561903.6 lgz_components.txt 
ILTJ141727.63+561903.6 ILTJ141729.59+561851.4 1
```
@wllwen007 Any ideas?

Just a general point when finding problems with the catalogue: please report the value of ID_Flag, so we can narrow this down as much as possible.

**Comment by wndywllms** [comment]
Yeah, this time it was a stupid bug in my code...  (randomizing the order of the sources with a np.unique call left over from an earlier version means the components no longer match up o_O)

fixed in c987a2bfea6479b0e485c7161d9b6b4d97e0db67 and merge_ID_v0.7 catalogues

> Probably unrelated, but still important (let me know if you want me to put this on a separate thread):
-There is a duplicate entry in the main table (ID=ILTJ132633.10+484745.7, ID_flag=1)

I noticed this one already - it is the 1/300k case where the source comes from two separate mosaics and because it is closer to the centre of both mosaics, it has been included twice. Dealt with by flagging higher noise one as an artefact.... but only in the next version of the catalouge.

fixed in c987a2bfea6479b0e485c7161d9b6b4d97e0db67 and merge_ID_v0.7 catalogues

> Maybe unrelated, less important, but will need looking into at some point (let me know if you want me to put this on a separate thread):
-There are 162 sources (160 from LGZ, plus the two from the duplicated entry above) for which the number of components listed on the main table and the number of associated entries in the components catalogue are different (in some cases, the number of entries in the components table is larger, in some cases smaller).

probably a separate issue... still present in the current version

**Comment by jcroston** [comment]
Thanks Wendy. @bmingo can you confirm what flag ID these 162 have? By "from LGZ" do you mean 311? If so then we can check the components list from the 0.7 components catalogue against my LGZv1 component catalogue (for which I think I sent you the location?) 

These could maybe be cases from the RA range where the components were from the earlier source catalogue and so they broke down into a different number of components once the catalogues were reconciled? If so then they should all be in the RA range 170 - 190: Beatriz can you check that too?

**Comment by mhardcastle** [comment]
I think @jcroston's suggestion is pretty plausible. My code doesn't correct the number of components in an unchanged LGZ entry (i.e. not 312) but it can trivially do so. Let's check this and if it is the problem I can fix it in the next release. Holding off on publishing the new catalogue till then.

**Comment by bmingo** [comment]
I updated my comment after seeing Martin's, with the ID values. Sorry, perhaps I should have posted a new comment instead.

I have saved the table on the LOFAR server, in /data/lofar/bmingo/morph/hetdex/Diff_comp_0.6b.fits (It contains all the columns from the main table, plus the number of components in the components table associated with each row, at the end).

The RA values range from 167 to 227, for the sources themselves. It is possible that the values for the components are different, due to the bug.

**Comment by wndywllms** [comment]
Ok, since we're now talking about the other issue here: where there are fewer components with the same New_Source_Name than LGZ_Assoc, in at least one case, this is because one of these components is flagged as an artefact in the first stage of the flowchart and therefore has it's New_Source_Name overridden as '' even though it has been associated in lgz. I guess it makes sense to keep them in the association...

**Comment by mhardcastle** [comment]
@wllwen007 I have made a new version of the LGZ catalogue where the number of components is explicitly counted for all entries -- `/data/lofar/mjh/hetdex_v4/lgz_v1/HETDEX-LGZ-cat-v0.7-filtered-zooms.fits`. If you can merge that in at some point (and maybe sort out the artefacts as well) then we can release another catalogue version.

**Comment by wndywllms** [comment]
I've updated the merged catalogues in  /data/lofar/wwilliams/hetdex/LoTSS-DR1-July21-2017/
LOFAR_HBA_T1_DR1_merge_ID_v0.7.comp.fits
LOFAR_HBA_T1_DR1_merge_ID_v0.7.fits

looks like the number of components always matches the LGZ_assoc value and the components of a given associated source live in the same part of the sky so hopefully these issues have all been resolved

**Comment by mhardcastle** [comment]
Thanks Wendy. Let's hope so. New version 0.5 catalogue is on the release site.
