### ISSUE TITLE
Resolved column?

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/lgz#15]
The formula 1.25 + 3.01*(peak_flux/isl_rms)**(-0.53) seems reasonable at separating resolved and unresolved sources. Do we want a column in the catalogue indicating whether a source is resolved (according to this formula). I dont mind either way really the the formula isnt perfect but perhaps its useful to give an indication.

**Comment by mhardcastle** [comment]
I would tend to think that's something to put in the readme for the catalogue -- because if someone comes up with a better formula then we haven't cast that one in stone in the catalogue. Looks like there are a few free parameters there that someone might want to tune. What is that a limit on? Maj? How do you know it's doing a good job?

**Comment by twshimwell** [comment]
OK fair enough.
