### ISSUE TITLE
LGZ sizes too large

### ISSUE THREAD

**Issue by wndywllms** [mhardcastle/lgz#28]
@mhardcastle I'm checking my 2MASX merging of components (uses Make_Shape) and the sizes seem too large by a factor 2. Shouldn't merging a single component give LGZ_Size, LGZ_Width \approx DC_Maj, DC_Min ? [should be an easy fix if you agree this is a problem...]

Plotting source LGZ_Size against component DC_Maj  for all LGZ/2MASX sources (obviously quite different for many component sources), but should be the same for single component, or all components contained within another (for 2MASX sources with only one component I'm setting LGZ_Size=DC_Maj):
![image](https://user-images.githubusercontent.com/2170761/35686148-816c2d90-0763-11e8-9422-fbbc063436b1.png)

**Comment by mhardcastle** [comment]
No, this is intentional. The reasoning is that 2*DC_Maj is a good estimate of what the actual size (as in largest extent) of a Gaussian with a FWHM of DC_Maj actually is. It can only be an estimate because sources aren't really Gaussians: that factor of 2 is about right in mapping between FWHM and diameter for optically thin projected spheres on the sky that have been fitted with Gaussians.

(For some context, remember that the ellipses we plot in visualizing this stuff have _semi_-major axis equal to Maj.)

**Comment by wndywllms** [comment]
Ok, that makes sense, should've thought about what I was comparing o_O (obviously anyone actually thinking about using largest angular extent type sizes would think this through or read the docs (which currently are a bit behind))

I'll fix my 'merged' single 2MASX sources.
