### ISSUE TITLE
Source missmatch between components and optical catalogue

### ISSUE THREAD

**Issue by nudomarinero** [mhardcastle/lgz#36]
There are 22 sources that are in the optical catalogue but not in the components one and 82 sources that are in the component catalogue but not in the optical one.

These sources can be found doing a exact value match in Topcat between the "Component_Name" column in the components table and the "Source_Name" column in the optical table with the settings "All matches" and "1 xor 2" .

**Comment by mhardcastle** [comment]
I think most of these we have already identified and fixed. But I will check again when we are ready to release v1.1 of the catalogue.

(I assume you mean 'Source_Name' and 'Source_Name'.)

**Comment by nudomarinero** [comment]
That is great, thanks. Yes, I meant 'Source_Name' and 'Source_Name'.

**Comment by mhardcastle** [comment]
@wllwen007 So in a technical sense we have fixed 'most of' Pepe's problem in current draft v1.1 because the 82 sources have all been fixed by dealing with compoverlap=1 sources.

However the 22 sources that are in the optical catalogue but not the component one persist. They are all LGZ sources and mostly single-component. On spot-checking they are real sources and they appear in my lgz_components.txt file. Any idea what's wrong here?

**Comment by mhardcastle** [comment]
This is now a test case, see #39

**Comment by wndywllms** [comment]
@mhardcastle I'm not entirely sure what the other 22 sources were (possibly related to the 2MASX/LGZ conflicts?), but in the process of tidying up my code and extracting a list of things removed as artefacts (either from the flowchart or lgz) (commit 498835cc97ee5803e90498337f31f0253a26e570), they  are now gone


> This is now a test case, see #39

so the latest draft v1.1 now on lofar passes all the tests

**Comment by mhardcastle** [comment]
Right, your draft v1.1 passes the test, mine, which includes the blends, doesn't. So in some way I don't understand these sources are going missing in the blend processing (in fact this is where all the remaining test failures appear).

I'll investigate.

**Comment by mhardcastle** [comment]
Ah, I see. In your component catalogue these sources have ID_flag=42 whereas in the corresponding source catalogue entries they have ID_flag=31. The blend code removes all the ID_flag==41 or 42 components and then recreates them, but they'll only be recreated if they have a corresponding entry in the ID_flag==41 or ID_flag==42 source catalogue list.

I guess there should be no circumstances where the ID_flags in the source and component tables disagree?

**Comment by mhardcastle** [comment]
(These are the only cases where they disagree.)

**Comment by wndywllms** [comment]
This is down to a silly bug o_O in the blend selection for sources and components (using >  and >= 0.5 for Blend_prob when a small number actually have this flag = 0.5). So the ~20 sources now have the blend ID_flags matching those in the component catalogue. I'm not sure if these will already have blend files or if they'll need to be done...
(fixed in ac4440e47774e0c1ef24666a9198bfe7eff7cd1f)

everything should have the same ID_flags in both the source and component catalogues 
(added a test for this 3ecd0ca2bf8897dc9567e6f377ccf25b70a4dd3f)

**Comment by mhardcastle** [comment]
Version 1.1 is released and passes the relevant test (woo hoo!)
